from twilio.rest import Client

# Your Account SID from twilio.com/console
account_sid = "AC9a17f90f9edc320da1af1f9ed59e182a"
# Your Auth Token from twilio.com/console
auth_token  = "1234567890"

client = Client(account_sid, auth_token)

message = client.messages.create(
    to="+1234567890", # your phone number
    from_="+1234567890", # your number generated by twilio
    body="You made a program that sent this message!")

print(message.sid)
